export const STUDENTS = [
  { id: "3001", name: "GUNJAN CHOWDHURY PRITY", email: "gunjanchowdhury1911@gmail.com" },
  { id: "3002", name: "AFRUJA AKTER MOON", email: "afrujaaktermoon@gmail.com" },
  { id: "3003", name: "MD ROHAN", email: "rssufian9914@gmail.com" },
  { id: "3004", name: "TAYEB HASAN NILOY", email: "niloy55554@gmail.com" },
  { id: "3005", name: "NUSRAT JAHAN", email: "nusrat132132@gmail.com" },
  { id: "3006", name: "KHURSHED ALAM BHUIYAN", email: "khurshedbhuiyan16@gmail.com" },
  { id: "3007", name: "RAZA UL BARI KHOKA", email: "razaulbari506@gmail.com" },
  { id: "3008", name: "JUBAYER MAHMUD SHAWON", email: "mahmudshawon555@gmail.com" },
  { id: "3009", name: "AVIJIT SAHA", email: "asaha2430535@bscse.uiu.ac.bd" },
  { id: "3010", name: "LABIBA TASNIM", email: "labibatasnim84@gmail.com" },
  { id: "3011", name: "MD. KAWSAR AHMED", email: "kawsar7t@gmail.com" },
  { id: "3012", name: "FARIHA SHARMIN", email: "fsharmin278@gmail.com" },
  { id: "3013", name: "SHAHEDUL ISLAM KHAN", email: "shahedulik6904@gmail.com" },
  { id: "3014", name: "ABDUR RAHMAN BHUYAN SEYAM", email: "bhuyanseyam4@gmail.com" },
  { id: "3015", name: "MIR AFTAB UDDIN", email: "miraftabuddin.bd.02@gmail.com" },
  { id: "3016", name: "MD SAMIUL ALAM", email: "iamsamiul2025@gmail.com" },
  { id: "3017", name: "FAHMIDA YASMIN TOMA", email: "fahmidatoma21@gmail.com" },
  { id: "3018", name: "MD AHSUN BHUIYAN ANAM", email: "itsanam777@gmail.com" },
  { id: "3019", name: "ALIF RAHMAN SETAB", email: "alifrahman1100@gmail.com" },
  { id: "3020", name: "SADIA AMIN MIM", email: "smim2430343@bscse.uiu.ac.bd" },
  { id: "3021", name: "MOHAMMED RAFI OSMANI", email: "rafiusmani81@gmail.com" },
  { id: "3022", name: "TANVIR AHMED NISHAD", email: "nishadtanvirahmed@gmail.com" },
  { id: "3023", name: "TUHAIFA TASNIM", email: "tasnimtuhaifa@gmail.com" },
  { id: "3024", name: "SAYADA FARHANA", email: "sfarhana2420572@bscse.uiu.ac.bd" },
  { id: "3025", name: "MEHEZABIN KHANAM", email: "mehezabinkhanam8@gmail.com" },
  { id: "3026", name: "MD TANVIR SHAHRIAR CHY TAMIM", email: "tsctamim05@gmail.com" },
  { id: "3027", name: "PROTTOY", email: "sayedprottoy368@gmail.com" },
  { id: "3028", name: "MOUMITA TASMIN", email: "moumitaemi@gmail.com" },
  { id: "3029", name: "NAHIAN MEGHLA", email: "meghlanahian905@gmail.com" },
  { id: "3030", name: "MD TAMIM HOSSAIN", email: "tamim.novonex@gmail.com" },
];

export const HW_LIST = [
  { id: "HW01", title: "Arrays & Strings" },
  { id: "HW02", title: "Linked List" },
  { id: "HW03", title: "Stack & Queue" },
  { id: "HW04", title: "Binary Search" },
  { id: "HW05", title: "Recursion" },
  { id: "HW06", title: "Trees" },
  { id: "HW07", title: "Graph BFS/DFS" },
  { id: "HW08", title: "Dynamic Programming" },
];